### ISSUE TITLE
'SpaceView3D' object has no attribute 'node_tree'

### ISSUE THREAD

**Issue by hsab** [hsab/GrowthNodes#13]
[From BlenderArtists](https://blenderartists.org/forum/showthread.php?444094-Addon-GrowthNodes-Explore-surface-growth-simulation&p=3276384&viewfull=1#post3276384)

unfortunately I get following error, if I press set first/last keyframe or "Bake Nodetree
File "....../scripts/addons/GrowthNodes-master/umog_addon/operators/frame_operators.py", line 13, in execute
tree = context.area.spaces.active.node_tree
AttributeError: 'SpaceView3D' object has no attribute 'node_tree'

Edit: It works fine in the Node Editor, but not in the 3D View.

**Comment by ItsmeDc** [comment]
Hello,
Any news on this issue?
I can't make it work on Blender 2.78/2.79/2.79b

**Comment by hsab** [comment]
Hey I've halted all development until 2.8 and their python API is finalized.
Will keep you posted.

**Comment by hsab** [comment]
Fixed
